/*
 * This file is part of AVRThermostat.
 *
 * (c) Artyom Protaskin <a.protaskin@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

#ifndef DISPLAY_H
#define DISPLAY_H

#include <stdint.h>
#include <avr/io.h> // The _BV() macro

#include "iodef.h"

// Digits
#define DISPLAY_1_MASK _BV(DISPLAY_1_BIT)
#define DISPLAY_2_MASK _BV(DISPLAY_2_BIT)
#define DISPLAY_3_MASK _BV(DISPLAY_3_BIT)
#define DISPLAY_4_MASK _BV(DISPLAY_4_BIT)

#define DISPLAY_DIGITS_MASK ( \
	DISPLAY_1_MASK | DISPLAY_2_MASK | DISPLAY_3_MASK | DISPLAY_4_MASK)

// Segments
#define DISPLAY_A_MASK  _BV(DISPLAY_A_BIT)
#define DISPLAY_B_MASK  _BV(DISPLAY_B_BIT)
#define DISPLAY_C_MASK  _BV(DISPLAY_C_BIT)
#define DISPLAY_D_MASK  _BV(DISPLAY_D_BIT)
#define DISPLAY_E_MASK  _BV(DISPLAY_E_BIT)
#define DISPLAY_F_MASK  _BV(DISPLAY_F_BIT)
#define DISPLAY_G_MASK  _BV(DISPLAY_G_BIT)
#define DISPLAY_DP_MASK _BV(DISPLAY_DP_BIT)

#define DISPLAY_SEGMENTS_MASK ( \
	DISPLAY_A_MASK | DISPLAY_B_MASK | DISPLAY_C_MASK | DISPLAY_D_MASK | \
	DISPLAY_E_MASK | DISPLAY_F_MASK | DISPLAY_G_MASK | DISPLAY_DP_MASK)

// Char masks
#define DISPLAY_CHAR_BLANK 0
#define DISPLAY_CHAR_POINT DISPLAY_DP_MASK
#define DISPLAY_CHAR_MINUS DISPLAY_G_MASK

#define DISPLAY_CHAR_0 ( \
	DISPLAY_A_MASK | DISPLAY_B_MASK | DISPLAY_C_MASK | DISPLAY_D_MASK | \
	DISPLAY_E_MASK | DISPLAY_F_MASK)

#define DISPLAY_CHAR_1 ( \
	DISPLAY_B_MASK | DISPLAY_C_MASK)

#define DISPLAY_CHAR_2 ( \
	DISPLAY_A_MASK | DISPLAY_B_MASK | DISPLAY_D_MASK | DISPLAY_E_MASK | \
	DISPLAY_G_MASK)

#define DISPLAY_CHAR_3 ( \
	DISPLAY_A_MASK | DISPLAY_B_MASK | DISPLAY_C_MASK | DISPLAY_D_MASK | \
	DISPLAY_G_MASK)

#define DISPLAY_CHAR_4 ( \
	DISPLAY_B_MASK | DISPLAY_C_MASK | DISPLAY_F_MASK | DISPLAY_G_MASK)

#define DISPLAY_CHAR_5 ( \
	DISPLAY_A_MASK | DISPLAY_C_MASK | DISPLAY_D_MASK | DISPLAY_F_MASK | \
	DISPLAY_G_MASK)

#define DISPLAY_CHAR_6 ( \
	DISPLAY_A_MASK | DISPLAY_C_MASK | DISPLAY_D_MASK | DISPLAY_E_MASK | \
	DISPLAY_F_MASK | DISPLAY_G_MASK)
	
#define DISPLAY_CHAR_7 ( \
	DISPLAY_A_MASK | DISPLAY_B_MASK | DISPLAY_C_MASK)

#define DISPLAY_CHAR_8 ( \
	DISPLAY_A_MASK | DISPLAY_B_MASK | DISPLAY_C_MASK | DISPLAY_D_MASK | \
	DISPLAY_E_MASK | DISPLAY_F_MASK | DISPLAY_G_MASK)

#define DISPLAY_CHAR_9 ( \
	DISPLAY_A_MASK | DISPLAY_B_MASK | DISPLAY_C_MASK | DISPLAY_D_MASK | \
	DISPLAY_F_MASK | DISPLAY_G_MASK)

#define DISPLAY_CHAR_A ( \
	DISPLAY_A_MASK | DISPLAY_B_MASK | DISPLAY_C_MASK | DISPLAY_E_MASK | \
	DISPLAY_F_MASK | DISPLAY_G_MASK)

#define DISPLAY_CHAR_C ( \
	DISPLAY_A_MASK | DISPLAY_D_MASK | DISPLAY_E_MASK | DISPLAY_F_MASK)

#define DISPLAY_CHAR_D ( \
	DISPLAY_B_MASK | DISPLAY_C_MASK | DISPLAY_D_MASK | DISPLAY_E_MASK | \
	DISPLAY_G_MASK)

#define DISPLAY_CHAR_E ( \
	DISPLAY_A_MASK | DISPLAY_D_MASK | DISPLAY_E_MASK | DISPLAY_F_MASK | \
	DISPLAY_G_MASK)

#define DISPLAY_CHAR_L ( \
	DISPLAY_D_MASK | DISPLAY_E_MASK | DISPLAY_F_MASK)

#define DISPLAY_CHAR_O ( \
	DISPLAY_A_MASK | DISPLAY_B_MASK | DISPLAY_C_MASK | DISPLAY_D_MASK | \
	DISPLAY_E_MASK | DISPLAY_F_MASK)

#define DISPLAY_CHAR_R ( \
	DISPLAY_E_MASK | DISPLAY_G_MASK)


#define DISPLAY_REGISTER_SIZE 4


extern const uint8_t display_numbers_map[10];

extern volatile uint8_t display_register[DISPLAY_REGISTER_SIZE];
extern uint8_t display_register_index;

void display_init(void);
void display_show(void);
void display_hide(void);
void display_next(void);
void display_drop_register(void);

#endif /* DISPLAY_H */
